### ISSUE TITLE
Sensors to Link Jobs

### ISSUE THREAD

**Issue by cyramic** [SocialFinanceDigitalLabs/liia-tools-pipeline#16]
We will need the following to be done in the liia-tools-pipeline repo

LA pipelines
- [ ] Rename "Location Sensor" to `ssda903_pipeline_sensor` This is what we can use in development and staging.
- [ ] We will need a schedule that will be turned on in production for this.  `ssda903_schedule`.  This is different than a sensor but will be a very similar idea and structure.  Examples of [sensors](here: https://docs.dagster.io/concepts/automation/schedules/examples)
- [ ] Add in a sensor (like the sufficiency sensor) to trigger the `ssda903_move_current` job once `ssda903_clean` completes
- [ ] Add in a sensor (like the sufficiency sensor) to trigger the `ssda903_concatenate` job once `ssda903_move_current` completes

Org Pipelines
- [ ] Create a new location-style sensor for the `ssda903_reports` job to run once changes in files are detected in the LA's shared folder
- [ ] Modify the sufficiency sensor to run once the `ssda903_reports` job completes

![Image](https://github.com/user-attachments/assets/acef9a35-ff89-48c5-8077-5326182e2c25)

**Comment by DJavur** [comment]
@DJavur to take up - Add in a sensor (like the sufficiency sensor) to trigger the ssda903_move_current job once ssda903_clean completes

**Comment by MichaelHanksSF** [comment]
@MichaelHanksSF to take up - Create a new location-style sensor for the ssda903_reports job to run once changes in files are detected in the LA's shared folder

**Comment by DJavur** [comment]
@DJavur to take up - Add in a sensor (like the sufficiency sensor) to trigger the ssda903_concatenate job once ssda903_move_current completes
